### ISSUE TITLE
blazor support

### ISSUE THREAD

**Issue by j209** [optimajet/DWKit#10]
Hi
any plan for .net core 3.1 and [blazor](https://github.com/aspnet/Blazor) support?

**Comment by optimajet** [comment]
Most likely we will switch to .net core 3.1 in one of the following releases. We will explore whether Blasor and/or web assemblies can be used to create DWKIT-based PWAs.  But it will be difficult to use  Blazor for DWKIT forms since they are written in the React and work differently from regular ASP.NET MVC views.
